<?php

class CurlException extends Exception
{
	
	static public $curl_errors = array(
		CURLE_UNSUPPORTED_PROTOCOL => 'CURLE_UNSUPPORTED_PROTOCOL',
		CURLE_FAILED_INIT => 'CURLE_FAILED_INIT',
		CURLE_URL_MALFORMAT => 'CURLE_URL_MALFORMAT',
		CURLE_URL_MALFORMAT_USER => 'CURLE_URL_MALFORMAT_USER',
		CURLE_COULDNT_RESOLVE_PROXY => 'CURLE_COULDNT_RESOLVE_PROXY',
		CURLE_COULDNT_RESOLVE_HOST => 'CURLE_COULDNT_RESOLVE_HOST',
		CURLE_COULDNT_CONNECT => 'CURLE_COULDNT_CONNECT',
		CURLE_FTP_WEIRD_SERVER_REPLY => 'CURLE_FTP_WEIRD_SERVER_REPLY',
		CURLE_REMOTE_ACCESS_DENIED => 'CURLE_REMOTE_ACCESS_DENIED',
		CURLE_FTP_WEIRD_PASS_REPLY => 'CURLE_FTP_WEIRD_PASS_REPLY',
		CURLE_FTP_WEIRD_PASV_REPLY => 'CURLE_FTP_WEIRD_PASV_REPLY',
		CURLE_FTP_WEIRD_227_FORMAT => 'CURLE_FTP_WEIRD_227_FORMAT',
		CURLE_FTP_CANT_GET_HOST => 'CURLE_FTP_CANT_GET_HOST',
		CURLE_FTP_COULDNT_SET_TYPE => 'CURLE_FTP_COULDNT_SET_TYPE',
		CURLE_PARTIAL_FILE => 'CURLE_PARTIAL_FILE',
		CURLE_FTP_COULDNT_RETR_FILE => 'CURLE_FTP_COULDNT_RETR_FILE',
		CURLE_QUOTE_ERROR => 'CURLE_QUOTE_ERROR',
		CURLE_HTTP_RETURNED_ERROR => 'CURLE_HTTP_RETURNED_ERROR',
		CURLE_WRITE_ERROR => 'CURLE_WRITE_ERROR',
		CURLE_UPLOAD_FAILED => 'CURLE_UPLOAD_FAILED',
		CURLE_READ_ERROR => 'CURLE_READ_ERROR',
		CURLE_OUT_OF_MEMORY => 'CURLE_OUT_OF_MEMORY',
		CURLE_OPERATION_TIMEDOUT => 'CURLE_OPERATION_TIMEDOUT',
		CURLE_FTP_PORT_FAILED => 'CURLE_FTP_PORT_FAILED',
		CURLE_FTP_COULDNT_USE_REST => 'CURLE_FTP_COULDNT_USE_REST',
		CURLE_RANGE_ERROR => 'CURLE_RANGE_ERROR',
		CURLE_HTTP_POST_ERROR => 'CURLE_HTTP_POST_ERROR',
		CURLE_SSL_CONNECT_ERROR => 'CURLE_SSL_CONNECT_ERROR',
		CURLE_BAD_DOWNLOAD_RESUME => 'CURLE_BAD_DOWNLOAD_RESUME',
		CURLE_FILE_COULDNT_READ_FILE => 'CURLE_FILE_COULDNT_READ_FILE',
		CURLE_LDAP_CANNOT_BIND => 'CURLE_LDAP_CANNOT_BIND',
		CURLE_LDAP_SEARCH_FAILED => 'CURLE_LDAP_SEARCH_FAILED',
		CURLE_FUNCTION_NOT_FOUND => 'CURLE_FUNCTION_NOT_FOUND',
		CURLE_ABORTED_BY_CALLBACK => 'CURLE_ABORTED_BY_CALLBACK',
		CURLE_BAD_FUNCTION_ARGUMENT => 'CURLE_BAD_FUNCTION_ARGUMENT',
		CURLE_INTERFACE_FAILED => 'CURLE_INTERFACE_FAILED',
		CURLE_TOO_MANY_REDIRECTS => 'CURLE_TOO_MANY_REDIRECTS',
		CURLE_UNKNOWN_TELNET_OPTION => 'CURLE_UNKNOWN_TELNET_OPTION',
		CURLE_TELNET_OPTION_SYNTAX => 'CURLE_TELNET_OPTION_SYNTAX',
		CURLE_PEER_FAILED_VERIFICATION => 'CURLE_PEER_FAILED_VERIFICATION',
		CURLE_GOT_NOTHING => 'CURLE_GOT_NOTHING',
		CURLE_SSL_ENGINE_NOTFOUND => 'CURLE_SSL_ENGINE_NOTFOUND',
		CURLE_SSL_ENGINE_SETFAILED => 'CURLE_SSL_ENGINE_SETFAILED',
		CURLE_SEND_ERROR => 'CURLE_SEND_ERROR',
		CURLE_RECV_ERROR => 'CURLE_RECV_ERROR',
		CURLE_SSL_CERTPROBLEM => 'CURLE_SSL_CERTPROBLEM',
		CURLE_SSL_CIPHER => 'CURLE_SSL_CIPHER',
		CURLE_SSL_CACERT => 'CURLE_SSL_CACERT',
		CURLE_BAD_CONTENT_ENCODING => 'CURLE_BAD_CONTENT_ENCODING',
		CURLE_LDAP_INVALID_URL => 'CURLE_LDAP_INVALID_URL',
		CURLE_FILESIZE_EXCEEDED => 'CURLE_FILESIZE_EXCEEDED',
		CURLE_USE_SSL_FAILED => 'CURLE_USE_SSL_FAILED',
		CURLE_SEND_FAIL_REWIND => 'CURLE_SEND_FAIL_REWIND',
		CURLE_SSL_ENGINE_INITFAILED => 'CURLE_SSL_ENGINE_INITFAILED',
		CURLE_LOGIN_DENIED => 'CURLE_LOGIN_DENIED',
		CURLE_TFTP_NOTFOUND => 'CURLE_TFTP_NOTFOUND',
		CURLE_TFTP_PERM => 'CURLE_TFTP_PERM',
		CURLE_REMOTE_DISK_FULL => 'CURLE_REMOTE_DISK_FULL',
		CURLE_TFTP_ILLEGAL => 'CURLE_TFTP_ILLEGAL',
		CURLE_TFTP_UNKNOWNID => 'CURLE_TFTP_UNKNOWNID',
		CURLE_REMOTE_FILE_EXISTS => 'CURLE_REMOTE_FILE_EXISTS',
		CURLE_TFTP_NOSUCHUSER => 'CURLE_TFTP_NOSUCHUSER',
		CURLE_CONV_FAILED => 'CURLE_CONV_FAILED',
		CURLE_CONV_REQD => 'CURLE_CONV_REQD',
		CURLE_SSL_CACERT_BADFILE => 'CURLE_SSL_CACERT_BADFILE',
		CURLE_REMOTE_FILE_NOT_FOUND => 'CURLE_REMOTE_FILE_NOT_FOUND',
		CURLE_SSH => 'CURLE_SSH',
		CURLE_SSL_SHUTDOWN_FAILED => 'CURLE_SSL_SHUTDOWN_FAILED',
		CURLE_AGAIN => 'CURLE_AGAIN',
		CURLE_SSL_CRL_BADFILE => 'CURLE_SSL_CRL_BADFILE',
		CURLE_SSL_ISSUER_ERROR => 'CURLE_SSL_ISSUER_ERROR',
		CURLE_FTP_PRET_FAILED => 'CURLE_FTP_PRET_FAILED',
		CURLE_RTSP_CSEQ_ERROR => 'CURLE_RTSP_CSEQ_ERROR',
		CURLE_RTSP_SESSION_ERROR => 'CURLE_RTSP_SESSION_ERROR',
		CURLE_FTP_BAD_FILE_LIST => 'CURLE_FTP_BAD_FILE_LIST',
		CURLE_CHUNK_FAILED => 'CURLE_CHUNK_FAILED'
	);
	
	function __construct( $curl_error_code )
	{
		if( array_key_exists( $curl_error_code, self::$curl_errors ) )
			throw new Exception( "Unknown \$curl_error_code: $curl_error_code" );
		
		parent::__construct( self::$curl_errors[$curl_error_code], $curl_error_code );
	}
	
}